### ISSUE TITLE
Le bouton de partage devrait partager le titre de la page aussi

### ISSUE THREAD

**Issue by pascalchevrel** [kernox/Mastodon-Share-Browser-Extension#14]
Quand on clique sur le bouton, seul un lien est partagé. Par défaut, ça devrait se comporter comme l'outil de partage de page de Firefox, créer un pouet avec le titre de la page (contenu de la balise <title>) et le lien.

**Comment by kernox** [comment]
Je prend note de votre suggestion. Merci
