### ISSUE TITLE
Text disappears  in compose box

### ISSUE THREAD

**Issue by ghost** [kernox/Mastodon-Share-Browser-Extension#15]
When this extension is enabled in Firefox (53.0.3, Ubuntu 17.04), text in a compose box disappears when clicking in it.

**Comment by kemenaran** [comment]
I noticed this issue too, and would never have though this is coming from this extension.

+1

**Comment by kernox** [comment]
What version of the extension did you use ? The last version already fix this issue.
What operating system did you use ?
And finally, what browser did you use ?

**Comment by ghost** [comment]
I tried it again with version 1.3.2 from addons.mozilla.org, but still the same problem.

I'm using Firefox 54.0 (64 bits) and mu operating system is Ubuntu GNOME 17.04 (Linux).

**Comment by Mozinet-fr** [comment]
I meet this issue sometimes too with Mastodon Share 0.3.2 on Firefox 54.0.1 (previous versions also) in Win64 7.

**Comment by kernox** [comment]
Yes it's due to Mastodon used framework. The next version will be code on the API. This bug don't exist later.

**Comment by ghost** [comment]
This is closed, but the current version (0.3.2) still has this problem. When will there be a new version?
