### ISSUE TITLE
Add License Information

### ISSUE THREAD

**Issue by thenanobel** [kernox/Mastodon-Share-Browser-Extension#22]
Add license information for this software.

As long as there is no license, it can't be considered as a [free software](https://www.gnu.org/licenses/license-list.html#NoLicense).

Thanks.

**Comment by kernox** [comment]
Hi,

Thank you for your interest
Mastodon Share Extension is now on GPL v3 License.

**Comment by thenanobel** [comment]
Hello,

Thanks for releasing Mastodon Share under GPLv3. Thanks.
