### ISSUE TITLE
Add repository link to Chrome Web store

### ISSUE THREAD

**Issue by shuuji3** [kernox/Mastodon-Share-Browser-Extension#24]
As there is no link to this repository at [Mastodon Share - Chrome Web Store](https://chrome.google.com/webstore/detail/mastodon-share/ngkommdldcakheaeoafgakbbiinkohom), I have to google to find this site. How about adding to the URL of this repository as the website of the extension?

**Comment by kernox** [comment]
You have this information at the bottom of the readme ;D

**Comment by kernox** [comment]
https://github.com/kernox/Mastodon-Share#lextension

**Comment by shuuji3** [comment]
Sorry, the missing link I said was not the link from the repository *to* the extension page, but *from* extension page to this repository.
