### ISSUE TITLE
Changing instance and access key was surprisingly difficult

### ISSUE THREAD

**Issue by Cassolotl** [kernox/Mastodon-Share-Browser-Extension#29]
I first linked the plugin with cybre.space, and then when I wanted to change it I tried removing the instance name and access key from the plugin settings page and clicking save - but it wouldn't let me save with the access key blank.

I tried entering the new instance (octodon.social) and clicking "Obtain Access Key" but that just threw up all kinds of error messages.

In the end I took a wild stab in the dark and revoked permission for the plugin in cybre.space settings. This worked.

So, maybe you should add a note somewhere on that page saying "to change your instance and access key you must revoke the existing session on the old Mastodon instance's settings page." Or something?

**Comment by kernox** [comment]
Hi

You need to set an https valid url for your instance.
Try and say me if you ever have troubles
