### ISSUE TITLE
Posting on Wordpress when using this plugin gives error message

### ISSUE THREAD

**Issue by Cassolotl** [kernox/Mastodon-Share-Browser-Extension#30]
`Error: "Failed to connect to 2001:bc8:3890:a100::1: Network is unreachable" - Code: 0`

on an otherwise blank white page. The URL of the page with the error message on it is http://www.polyinpictures.com/wp-admin/post.php and I got there from http://www.polyinpictures.com/wp-admin/post-new.php by clicking "Publish".

The post was posted to my Wordpress blog, though, and the toot was sent to my account on octodon.social.

**Comment by kernox** [comment]
Hi !
Your are not in the right repository, this is the google and firefox extension here.

Please try the new version of Mastodon Share for WordPress, some bugs fixed

I close this issue.
