### ISSUE TITLE
Language selection only applied to setting screen

### ISSUE THREAD

**Issue by kuropen** [kernox/Mastodon-Share-Browser-Extension#31]
I am using Firefox 57 in Japanese language environment.

The language selection in setting screen seems to be only applied to the settings screen itself.
The compose box is still in French when English is specified in the setting.

![2017-11-17 23 00 07](https://user-images.githubusercontent.com/538708/32950901-6115492c-cbeb-11e7-8202-4fca097c342a.png)

**Comment by kernox** [comment]
Thank you for your interest.
You are right. And this thing will be fixed soon.

**Comment by kernox** [comment]
Hi ! We have made some modifications on the plugin.

Because we don't speak japanese, you can help for translation.

Edit this file ;) Thanks
https://github.com/kernox/Mastodon-Share-Browser-Extension/blob/master/src/all/assets/locales/ja.json

**Comment by kuropen** [comment]
@kernox Thank you for your notification.
I have added some translations as #34 . Please have a look that.

**Comment by kernox** [comment]
Thanks its merged ;)

**Comment by kernox** [comment]
Hi thé new version fixe this issue. Please update ;)
