### ISSUE TITLE
Extension causes unintended wiping of all typed text upon mouse left-click in text input field Mastodon web UI 

### ISSUE THREAD

**Issue by mzandbelt** [kernox/Mastodon-Share-Browser-Extension#36]
I encountered a very annoying bug in Firefox (linux) when using the Mastodon web UI. Whenever I wanted to correct a typo and I left-clicked my mouse just anywhere in the composed text of the input field all text was cleared and lost, so I had to start typing my whole message again! 
Just today found out that disabling this Mastodon Share extension in my Firefox settings solved the issue.
Please have a look to the code what might have caused this unintended left-mouseclick action.

**Comment by kernox** [comment]
Hi! the last version fix this issue
