### ISSUE TITLE
The text in compose window is transparent and not visible

### ISSUE THREAD

**Issue by novadeviator** [kernox/Mastodon-Share-Browser-Extension#41]
For some reason the text in the compose window is not visible unless you select it.
This is version 0.5 on FF 59.

In the screenshot I have selected part of the text.

![screenshot - 30 09 2018 - 20 33 59](https://user-images.githubusercontent.com/744626/46261200-6629a300-c4f0-11e8-9aca-ad50368f0fff.png)

**Comment by kernox** [comment]
Thanks for your report.

**Comment by Anglodel** [comment]
This issue is still there with me.
I'm using Firefox 66.0.5, a dark theme with Firefox and a dark theme with GTK/Xfce. 
![Capture d’écran_2019-06-10_15-36-26](https://user-images.githubusercontent.com/49619493/59199434-3d38d200-8b96-11e9-8373-72438191593a.png)
