### ISSUE TITLE
Unable to share from Twitter to Mastodon

### ISSUE THREAD

**Issue by oschwand** [kernox/Mastodon-Share-Browser-Extension#48]
The "Share to Mastodon" item in the menu of a tweet does not appear for me.

I am using Firefox. Please note that I am not logged in Tweeter since I do not have any Tweeter account.

**Comment by kernox** [comment]
Since the twitter page structure update, this feature no more work.
And no solution yet to restore that.

**Comment by kernox** [comment]
This feature will not be in the extension anymore for obvious reasons.
