### ISSUE TITLE
New installation, unable to get accesskey

### ISSUE THREAD

**Issue by vincentxavier** [kernox/Mastodon-Share-Browser-Extension#49]
On a new installation on Debian/Sid with Firefox 69.0 the extension doesn't present the api key nor the auth section and is thusly unusable

**Comment by kernox** [comment]
Thank you for this report.

**Comment by vincentxavier** [comment]
Do you need any additional information ?

**Comment by kernox** [comment]
No it's good, but just need to find time to fix it ;)
As you can see, i didn't do modifications on this project for a long time.

New version in developpment.

**Comment by kernox** [comment]
Fixed in the new release
