### ISSUE TITLE
Feature request: content warnings

### ISSUE THREAD

**Issue by teslasmoustache** [kernox/Mastodon-Share-Browser-Extension#51]
This add-on does not currently allow users to set content warnings. Which would be very good to be able to do.

**Comment by kernox** [comment]
Coming soon

![Capture d’écran du 2023-07-20 17-17-22](https://github.com/kernox/Mastodon-Share-Browser-Extension/assets/10383373/9b3ba1cd-730d-4314-bbbc-a093707dce54)
