### ISSUE TITLE
Can not connect to the instance

### ISSUE THREAD

**Issue by ghost** [kernox/Mastodon-Share-Browser-Extension#52]
Hi,
with the Firefox browser (beta version) in version 85.0b4 it is no longer possible to share a web page. With version 84.0 and beta versions of 84 it works fine. What can I do to make this work again?

Michael

**Comment by ddeimeke** [comment]
I confirm this behavior with Firefox 85.0.1 (no beta).

**Comment by fenix011** [comment]
I'm having issues too ...

> 85.0.1 Firefox version here

**Comment by Roboron3042** [comment]
Try obtaining the access code again. It worked for me.
