### ISSUE TITLE
Clicking away clears the module

### ISSUE THREAD

**Issue by Scofis** [kernox/Mastodon-Share-Browser-Extension#66]
Browser: FireFox

How it presents: When clicking on the Masto Share button in the navigation bar, the posting module appears. We can start adding to or modifying the text in the module. If the user clicks anywhere outside of the module, the module closes. And any additions/modifications to the post are lost.

Issue:  When making a post and trying to craft it, several things could require clicking outside the module (important notification, pausing a vid for IRL reasons, etc). Sometimes this cannot be avoided. As well as reasons related to crafting the post (checking the wording of the article to ensure accuracy of the post). However, doing so deletes all progress in making the post. Requiring recreating that progress. I can just open the module, copy the text that appears there, then open a tab to normal Masto to paste there. But then that essentially is making a extra step in doing a normal Masto post. And this add-on only gets a fraction of its use. 

Suggestion: Make the module permanently open until either the Toot button is pressed, or exited using an X button in the corner. This would ensure it does not close unintentionally. Or implement a minimize feature so it reduces the chance it will cover something. Or if possible, give the module memory that the user can return to it without loss of progress.

I am very grateful for the add-on. It has been very helpful. But this issue has been very annoying as well. I present this in the hopes that something can be done about it. Not sure if the suggestions are possible, but I wanted to present them in case they are helpful.

Thank you.

**Comment by Skembear** [comment]
Came here for the exact same reason. I am finding having to open notepad to write what I want to write after the link, a little too much. This issue is making the extension redundant. It is just as easy to copy and paste the link into Mastodon itself and browse back to pages to copy info from there

**Comment by kernox** [comment]
This problem is solved on the next release. Now each tabs memorize the toot associated.

**Comment by Skembear** [comment]
Thats fantastic Kernox. Thank you so much

**Comment by Scofis** [comment]
Thank you
